// Generated by claude-documenter — screenshot-orchestrator
// Do not edit manually; regenerate with /document or /documenter-do "re-capture screenshots"

import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

const BASE_URL = process.env.DOCUMENTER_BASE_URL || 'http://localhost:3000';
const OUTPUT_DIR = process.env.DOCUMENTER_OUTPUT_DIR || '.documenter/screenshots/web';

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

// ROUTES_PLACEHOLDER — replaced at generation time with per-route test blocks
// Example generated output:
//
// test('screenshot: login', async ({ page }) => {
//   await page.goto(`${BASE_URL}/login`);
//   await page.waitForLoadState('networkidle');
//   await page.screenshot({
//     path: path.join(OUTPUT_DIR, 'login.png'),
//     fullPage: true,
//   });
// });

{{ROUTE_TESTS}}
